routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\CatagoryController;
use App\Http\Controllers\UnitController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\PosController;
use App\Http\Middleware\login;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//user controller start
Route::get("user.index",[UserController::class,"index"]);
Route::get("user.create",[UserController::class,"create"]);
Route::post("user.store",[UserController::class,"store"]);
 Route::resource('users',UserController::class);

//user controller end
Route::post("login",[LoginController::class,"login"]);
Route::get("logout",[LoginController::class,"logout"]);


Route::get('/dashboard', function () {

    return view('pages.dashboard');
})->middleware('secured');



Route::get(md5('blank'), function () {
    return view('pages.blank');
})->name('blank');

Route::get('/', function () {
    return view('layouts.login');
});

//employee route
// Route::get('add-employee','EmployeeController@index')->name('add.employee');

// Route::get(md5("add-employee"),[EmployeeController::class,"index"]);

//Route::get("add-employee",[EmployeeController::class,"index"]);

// Route::post("employee.insert-employee",[EmployeeController::class,"store"]);
// Route::get("employee.all-employee",[EmployeeController::class,"Employees"]);
// Route::resource(md5("employee.add-employee"),EmployeeController::class)->middleware('secured');

// Route::resource("employee.add-employee",EmployeeController::class)->middleware('secured');
Route::get("employee.index",[EmployeeController::class,"index"]);
Route::get("employee.create",[EmployeeController::class,"create"]);
Route::post("employee.store",[EmployeeController::class,"store"]);
 Route::resource('employees',EmployeeController::class);


 //Route::resource('attendances','App\Http\Controllers\AttendanceController');
  Route::resource('attendances',AttendanceController::class)->middleware('secured');
  Route::resource('customers',CustomerController::class)->middleware('secured');
  Route::resource('catagorys',CatagoryController::class)->middleware('secured');
  Route::resource('units',UnitController::class)->middleware('secured');
  Route::resource('settings',SettingController::class)->middleware('secured');
  Route::resource('suppliers',SupplierController::class)->middleware('secured');
  Route::resource('products',ProductController::class)->middleware('secured');
  Route::resource('poss',PosController::class)->middleware('secured');
 //Route::resource('customers','App\Http\Controllers\CustomerController');

app/Models/Unit.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Unit extends Model
{
    use HasFactory;
    protected $fillable = [
        'name',
];
}

app/Http/Controllers/UnitController.php
<?php

namespace App\Http\Controllers;

use App\Models\Unit;
use Illuminate\Http\Request;

class UnitController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $units = Unit::latest()->paginate(20);
        return view('units.index',compact('units'))
        ->with('i', (request()->input('page',1) - 1)*20);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('units.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
        ]);
        Unit::create($request->all());
        return redirect()->route('units.index')
        ->with('success','Unit created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Unit  $unit
     * @return \Illuminate\Http\Response
     */
    public function show(Unit $unit)
    {
        return view('units.show',compact('unit'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Unit  $unit
     * @return \Illuminate\Http\Response
     */
    public function edit(Unit $unit)
    {
        return view('units.edit',compact('unit'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Unit  $unit
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Unit $unit)
    {
        $request->validate([

        ]);
        $unit->update($request->all());
        return redirect()->route('units.index')
        ->with('success','Unit Update Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Unit  $unit
     * @return \Illuminate\Http\Response
     */
    public function destroy(Unit $unit)
    {
        $unit->delete();
        return redirect()->route('units.index')
        ->with('success','Unit deleted successfully');
    }
}

resources/views/units/create.blade.php
@extends('layouts.app')

@section('title')

Add Unit
@endsection

@section("page")

<nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="{{url('/dashboard')}}">Dashboard</a>
                <a class="navbar-brand" href="{{url('/blank')}}">Contacts</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-align-justify"></i>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="javascript:void(0);" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Application</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="javascript:void(0);">Inbox</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="javascript:void(0);">Calendar</a>
                            <a class="dropdown-item" href="javascript:void(0);">TaskBoard</a>
                            <a class="dropdown-item" href="javascript:void(0);">Chat App</a>
                            <a class="dropdown-item" href="javascript:void(0);">Contacts</a>
                        </div>
                    </li>
                    </ul>
                    <form class="form-inline my-2 my-lg-0">
                        <button type="button" class="btn btn-primary">Add</button>
                        <a href="#" title="Portfolio" class="btn btn-success ml-2">Portfolio</a>
                    </form>
                </div>
            </nav>
            <div class="container-fluid">
                <div class="row clearfix">
                    <div class="col-lg-12 col-md-12">
                        <div class="card planned_task">
                            <div class="header">
                      
                                <button class="btn btn-info "><a href="{{route('units.index')}}">Manage catagory</a></button>
                            </div>
                            <div class="body">
                            <div class="col-md-12">
                        <div class="card">
                          
                            <div class="body">
                                <form id="basic-form" method="POST" action="{{route('units.store')}}" >
                                    @csrf
                                    <div class="form-group">
                                        <label> Unit Name   </label>
                                        <input type="text" name="name" class="form-control" placehoder="units Name" required>
                                    </div>
                                    <button type="submit" class="btn btn-primary">Add Customer </button>
                                </form>
                            </div>
                        </div>
                    </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
               
            @endsection

resources/views/units/edit.blade.php
@extends('layouts.app')

@section('title')

Edit Unit
@endsection

@section("page")

<nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="{{url('/dashboard')}}">Dashboard</a>
                <a class="navbar-brand" href="{{url('/blank')}}">Contacts</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-align-justify"></i>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="javascript:void(0);" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Application</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="javascript:void(0);">Inbox</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="javascript:void(0);">Calendar</a>
                            <a class="dropdown-item" href="javascript:void(0);">TaskBoard</a>
                            <a class="dropdown-item" href="javascript:void(0);">Chat App</a>
                            <a class="dropdown-item" href="javascript:void(0);">Contacts</a>
                        </div>
                    </li>
                   
                    </ul>
                    <form class="form-inline my-2 my-lg-0">
                        <button type="button" class="btn btn-primary">Add</button>
                        <a href="https://themeforest.net/user/wrraptheme/portfolio" title="Portfolio" class="btn btn-success ml-2">Portfolio</a>
                    </form>
                </div>
            </nav>
            <div class="container-fluid">
                <div class="row clearfix">
                    <div class="col-lg-12 col-md-12">
                        <div class="card planned_task">
                            <div class="header">
                                <h2><a href="{{route('units.index')}}">Manage Attendance</a></h2>
                            </div>
                            <div class="body">
                            <div class="col-md-12">
                        <div class="card">
                          
                            <div class="body">
                                <form id="basic-form" method="POST" action="{{ route('units.update',$unit->id) }}" >
                                    @csrf
                                    @method('PUT')
                                    <div class="form-group">
                                        <label> Name   </label>
                                        <input type="text" name="name" value="{{$unit->name}}" class="form-control" placehoder="Unit Name" required>
                                    </div>
                        
                                    <button type="submit" class="btn btn-primary">Update Unit</button>
                                </form>
                            </div>
                        </div>
                    </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
               
            @endsection

resources/views/units/index.blade.php
 
@extends('layouts.app')

@section('title')

Add Unit 
@endsection

@section("page")


<nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="{{url('/dashboard')}}">Dashboard</a>
                <a class="navbar-brand" href="{{url('/blank')}}">Contacts</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-align-justify"></i>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="javascript:void(0);" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Application</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="javascript:void(0);">Inbox</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="javascript:void(0);">Calendar</a>
                            <a class="dropdown-item" href="javascript:void(0);">TaskBoard</a>
                            <a class="dropdown-item" href="javascript:void(0);">Chat App</a>
                            <a class="dropdown-item" href="javascript:void(0);">Contacts</a>
                        </div>
                    </li>
                  
                    </ul>
                    <form class="form-inline my-2 my-lg-0">
                        <button type="button" class="btn btn-primary">Add</button>
                        <a href="https://themeforest.net/user/wrraptheme/portfolio" title="Portfolio" class="btn btn-success ml-2">Portfolio</a>
                    </form>
                </div>
            </nav>
            <div class="container-fluid">
                <div class="row clearfix">
                    <div class="col-lg-12 col-md-12">
                        <div class="card ">
                            <div class="header">
                            <!-- <h2><a href="{{url('customer.create')}}">Create Customer</a></h2> -->
                            <button class="btn btn-info "><a href="{{route('units.create')}}">Create Unit</a></button>
                            </div>
                            <div class="body">
                                @if($message = Session::get('success'))
                                <div class='alert alert-success alert-dismissible'>
                                <button type='button' class='close' data-dismiss='alert' aria-hidden='true'>×</button>
                                <h5><i class=icon fas fa-check></i>{{ $message }}</h5>  
                            </div>
                                @endif 
                                <div class="table-responsive">
                                <table class="table table-striped table-hover js-basic-example dataTable">
                                    
                                <thead>
                                            <tr>
                                                <th>SN</th>
                                                <th data-breakpoints="xs">Name</th>
                                                
                                                <th data-breakpoints="xs" style="float:right;text-align:center;">Action</th>
                                            </tr>
                                        </thead>
              <tbody>
                  @foreach($units as $unit)
                  <tr>
                      
                      <td> {{ ++$i }} </td>
                      <td> {{$unit->name}} </td>
                    
                 
                      <td class="project-actions text-right">
                         <form action="{{route('units.destroy',$unit->id)}}"method="POST">
                      <a class="btn btn-primary btn-sm" href="{{route('units.show',$unit->id)}}">                  
                              View
                          </a>
                          <a class="btn btn-info btn-sm" href="{{route('units.edit',$unit->id)}}">
              
                              Edit
                          </a>
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                            </form>  
                          </a>
                      </td>
                  </tr>
                 @endforeach
              </tbody>
          </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    
            @endsection