routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\CatagoryController;
use App\Http\Controllers\UnitController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\PosController;
use App\Http\Middleware\login;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//user controller start
Route::get("user.index",[UserController::class,"index"]);
Route::get("user.create",[UserController::class,"create"]);
Route::post("user.store",[UserController::class,"store"]);
 Route::resource('users',UserController::class);

//user controller end
Route::post("login",[LoginController::class,"login"]);
Route::get("logout",[LoginController::class,"logout"]);


Route::get('/dashboard', function () {

    return view('pages.dashboard');
})->middleware('secured');



Route::get(md5('blank'), function () {
    return view('pages.blank');
})->name('blank');

Route::get('/', function () {
    return view('layouts.login');
});

//employee route
// Route::get('add-employee','EmployeeController@index')->name('add.employee');

// Route::get(md5("add-employee"),[EmployeeController::class,"index"]);

//Route::get("add-employee",[EmployeeController::class,"index"]);

// Route::post("employee.insert-employee",[EmployeeController::class,"store"]);
// Route::get("employee.all-employee",[EmployeeController::class,"Employees"]);
// Route::resource(md5("employee.add-employee"),EmployeeController::class)->middleware('secured');

// Route::resource("employee.add-employee",EmployeeController::class)->middleware('secured');
Route::get("employee.index",[EmployeeController::class,"index"]);
Route::get("employee.create",[EmployeeController::class,"create"]);
Route::post("employee.store",[EmployeeController::class,"store"]);
 Route::resource('employees',EmployeeController::class);


 //Route::resource('attendances','App\Http\Controllers\AttendanceController');
  Route::resource('attendances',AttendanceController::class)->middleware('secured');
  Route::resource('customers',CustomerController::class)->middleware('secured');
  Route::resource('catagorys',CatagoryController::class)->middleware('secured');
  Route::resource('units',UnitController::class)->middleware('secured');
  Route::resource('settings',SettingController::class)->middleware('secured');
  Route::resource('suppliers',SupplierController::class)->middleware('secured');
  Route::resource('products',ProductController::class)->middleware('secured');
  Route::resource('poss',PosController::class)->middleware('secured');
 //Route::resource('customers','App\Http\Controllers\CustomerController');

app/Models/Catagory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Catagory extends Model
{
    use HasFactory;
    protected $fillable = [
        'name',
];
}

app/Http/Controllers/CatagoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Catagory;
use Illuminate\Http\Request;

class CatagoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $catagorys = Catagory::latest()->paginate(20);
        return view('catagorys.index',compact('catagorys'))
        ->with('i', (request()->input('page',1) - 1)*20);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('catagorys.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
        ]);
        Catagory::create($request->all());
        return redirect()->route('catagorys.index')
        ->with('success','catagory created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Catagory  $catagory
     * @return \Illuminate\Http\Response
     */
    public function show(Catagory $catagory)
    {
        return view('catagorys.show',compact('catagory'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Catagory  $catagory
     * @return \Illuminate\Http\Response
     */
    public function edit(Catagory $catagory)
    {
        return view('catagorys.edit',compact('catagory'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Catagory  $catagory
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Catagory $catagory)
    {
        $request->validate([

        ]);
        $catagory->update($request->all());
        return redirect()->route('catagorys.index')
        ->with('success','catagory Update Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Catagory  $catagory
     * @return \Illuminate\Http\Response
     */
    public function destroy(Catagory $catagory)
    {
        $catagory->delete();
        return redirect()->route('catagorys.index')
        ->with('success','catagory deleted successfully');
    }
}

resources/views/catagorys/create.blade.php
@extends('layouts.app')

@section('title')

Add Catagory
@endsection

@section("page")

<nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="{{url('/dashboard')}}">Dashboard</a>
                <a class="navbar-brand" href="{{url('/blank')}}">Contacts</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-align-justify"></i>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="javascript:void(0);" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Application</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="javascript:void(0);">Inbox</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="javascript:void(0);">Calendar</a>
                            <a class="dropdown-item" href="javascript:void(0);">TaskBoard</a>
                            <a class="dropdown-item" href="javascript:void(0);">Chat App</a>
                            <a class="dropdown-item" href="javascript:void(0);">Contacts</a>
                        </div>
                    </li>
                    </ul>
                    <form class="form-inline my-2 my-lg-0">
                        <button type="button" class="btn btn-primary">Add</button>
                        <a href="#" title="Portfolio" class="btn btn-success ml-2">Portfolio</a>
                    </form>
                </div>
            </nav>
            <div class="container-fluid">
                <div class="row clearfix">
                    <div class="col-lg-12 col-md-12">
                        <div class="card planned_task">
                            <div class="header">
                      
                                <button class="btn btn-info "><a href="{{route('catagorys.index')}}">Manage catagory</a></button>
                            </div>
                            <div class="body">
                            <div class="col-md-12">
                        <div class="card">
                          
                            <div class="body">
                                <form id="basic-form" method="POST" action="{{route('catagorys.store')}}" >
                                    @csrf
                                    <div class="form-group">
                                        <label> Catagory Name   </label>
                                        <input type="text" name="name" class="form-control" placehoder="catagorys Name" required>
                                    </div>
                                    <button type="submit" class="btn btn-primary">Add Customer </button>
                                </form>
                            </div>
                        </div>
                    </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
               
            @endsection

resources/views/catagorys/edit.blade.php
@extends('layouts.app')

@section('title')

Edit Catagory
@endsection

@section("page")

<nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="{{url('/dashboard')}}">Dashboard</a>
                <a class="navbar-brand" href="{{url('/blank')}}">Contacts</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-align-justify"></i>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="javascript:void(0);" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Application</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="javascript:void(0);">Inbox</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="javascript:void(0);">Calendar</a>
                            <a class="dropdown-item" href="javascript:void(0);">TaskBoard</a>
                            <a class="dropdown-item" href="javascript:void(0);">Chat App</a>
                            <a class="dropdown-item" href="javascript:void(0);">Contacts</a>
                        </div>
                    </li>
                   
                    </ul>
                    <form class="form-inline my-2 my-lg-0">
                        <button type="button" class="btn btn-primary">Add</button>
                        <a href="https://themeforest.net/user/wrraptheme/portfolio" title="Portfolio" class="btn btn-success ml-2">Portfolio</a>
                    </form>
                </div>
            </nav>
            <div class="container-fluid">
                <div class="row clearfix">
                    <div class="col-lg-12 col-md-12">
                        <div class="card planned_task">
                            <div class="header">
                                <h2><a href="{{route('catagorys.index')}}">Manage Attendance</a></h2>
                            </div>
                            <div class="body">
                            <div class="col-md-12">
                        <div class="card">
                          
                            <div class="body">
                                <form id="basic-form" method="POST" action="{{ route('catagorys.update',$catagory->id) }}" >
                                    @csrf
                                    @method('PUT')
                                    <div class="form-group">
                                        <label> Name   </label>
                                        <input type="text" name="name" value="{{$catagory->name}}" class="form-control" placehoder="customers Name" required>
                                    </div>
                        
                                    <button type="submit" class="btn btn-primary">Update Catagory</button>
                                </form>
                            </div>
                        </div>
                    </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
               
            @endsection

resources/views/catagorys/index.blade.php
 
@extends('layouts.app')

@section('title')

Add Catagory 
@endsection

@section("page")


<nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="{{url('/dashboard')}}">Dashboard</a>
                <a class="navbar-brand" href="{{url('/blank')}}">Contacts</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-align-justify"></i>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="javascript:void(0);" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Application</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="javascript:void(0);">Inbox</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="javascript:void(0);">Calendar</a>
                            <a class="dropdown-item" href="javascript:void(0);">TaskBoard</a>
                            <a class="dropdown-item" href="javascript:void(0);">Chat App</a>
                            <a class="dropdown-item" href="javascript:void(0);">Contacts</a>
                        </div>
                    </li>
                  
                    </ul>
                    <form class="form-inline my-2 my-lg-0">
                        <button type="button" class="btn btn-primary">Add</button>
                        <a href="https://themeforest.net/user/wrraptheme/portfolio" title="Portfolio" class="btn btn-success ml-2">Portfolio</a>
                    </form>
                </div>
            </nav>
            <div class="container-fluid">
                <div class="row clearfix">
                    <div class="col-lg-12 col-md-12">
                        <div class="card planned_task">
                            <div class="header">
                            <!-- <h2><a href="{{url('customer.create')}}">Create Customer</a></h2> -->
                            <button class="btn btn-info "><a href="{{route('catagorys.create')}}">Create catagory</a></button>
                            </div>
                            <div class="body">
                                @if($message = Session::get('success'))
                                <div class='alert alert-success alert-dismissible'>
                                <button type='button' class='close' data-dismiss='alert' aria-hidden='true'>×</button>
                                <h5><i class=icon fas fa-check></i>{{ $message }}</h5>  
                            </div>
                                @endif 
                                <div class="table-responsive">
                                <table class="table table-striped table-hover js-basic-example dataTable">
                                    
                                <thead>
                                            <tr>
                                                <th>SN</th>
                                                <th data-breakpoints="xs">Name</th>
                                                
                                                <th data-breakpoints="xs" style="float:right;text-align:center;">Action</th>
                                            </tr>
                                        </thead>
              <tbody>
                  @foreach($catagorys as $catagory)
                  <tr>
                      
                      <td> {{ ++$i }} </td>
                      <td> {{$catagory->name}} </td>
                    
                 
                      <td class="project-actions text-right">
                         <form action="{{route('catagorys.destroy',$catagory->id)}}"method="POST">
                      <a class="btn btn-primary btn-sm" href="{{route('catagorys.show',$catagory->id)}}">                  
                              View
                          </a>
                          <a class="btn btn-info btn-sm" href="{{route('catagorys.edit',$catagory->id)}}">
              
                              Edit
                          </a>
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                            </form>  
                          </a>
                      </td>
                  </tr>
                 @endforeach
              </tbody>
          </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    
            @endsection