routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\CatagoryController;
use App\Http\Controllers\UnitController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\PosController;
use App\Http\Middleware\login;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//user controller start
Route::get("user.index",[UserController::class,"index"]);
Route::get("user.create",[UserController::class,"create"]);
Route::post("user.store",[UserController::class,"store"]);
 Route::resource('users',UserController::class);

//user controller end
Route::post("login",[LoginController::class,"login"]);
Route::get("logout",[LoginController::class,"logout"]);


Route::get('/dashboard', function () {

    return view('pages.dashboard');
})->middleware('secured');



Route::get(md5('blank'), function () {
    return view('pages.blank');
})->name('blank');

Route::get('/', function () {
    return view('layouts.login');
});

//employee route
// Route::get('add-employee','EmployeeController@index')->name('add.employee');

// Route::get(md5("add-employee"),[EmployeeController::class,"index"]);

//Route::get("add-employee",[EmployeeController::class,"index"]);

// Route::post("employee.insert-employee",[EmployeeController::class,"store"]);
// Route::get("employee.all-employee",[EmployeeController::class,"Employees"]);
// Route::resource(md5("employee.add-employee"),EmployeeController::class)->middleware('secured');

// Route::resource("employee.add-employee",EmployeeController::class)->middleware('secured');
Route::get("employee.index",[EmployeeController::class,"index"]);
Route::get("employee.create",[EmployeeController::class,"create"]);
Route::post("employee.store",[EmployeeController::class,"store"]);
 Route::resource('employees',EmployeeController::class);


 //Route::resource('attendances','App\Http\Controllers\AttendanceController');
  Route::resource('attendances',AttendanceController::class)->middleware('secured');
  Route::resource('customers',CustomerController::class)->middleware('secured');
  Route::resource('catagorys',CatagoryController::class)->middleware('secured');
  Route::resource('units',UnitController::class)->middleware('secured');
  Route::resource('settings',SettingController::class)->middleware('secured');
  Route::resource('suppliers',SupplierController::class)->middleware('secured');
  Route::resource('products',ProductController::class)->middleware('secured');
  Route::resource('poss',PosController::class)->middleware('secured');
 //Route::resource('customers','App\Http\Controllers\CustomerController');

app/Models/Setting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    use HasFactory;
    protected $fillable = [
        'name','phone','address','email','logo','city','country',
    ];

}

app/Http/Controllers/SettingController.php
<?php

namespace App\Http\Controllers;

use App\Models\Setting;
use Illuminate\Http\Request;

class SettingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $settings = Setting::latest()->paginate(20);
        return view('settings.index',compact('settings'))
        ->with('i', (request()->input('page',1) - 1)*20);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('settings.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'phone' => 'required',
            'address' => 'required',
            'email' => 'required',
            'logo' => 'required',
            'city' => 'required',
            'country' => 'required',
        ]);
        Setting::create($request->all());
        return redirect()->route('settings.index')
        ->with('success','customer created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function show(Setting $setting)
    {
        return view('settings.show',compact('setting'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function edit(Setting $setting)
    {
        return view('settings.edit',compact('setting'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Setting $setting)
    {
        $request->validate([

        ]);
        $setting->update($request->all());
        return redirect()->route('settings.index')
        ->with('success','Setting Update Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function destroy(Setting $setting)
    {
        $setting->delete();
        return redirect()->route('settings.index')
        ->with('success','Settings deleted successfully');
    }
}

resources/views/settings/create.blade.php
@extends('layouts.app')

@section('title')

Add Settings
@endsection

@section("page")

<nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="{{url('/dashboard')}}">Dashboard</a>
                <a class="navbar-brand" href="{{url('/blank')}}">Contacts</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-align-justify"></i>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="javascript:void(0);" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Application</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="javascript:void(0);">Inbox</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="javascript:void(0);">Calendar</a>
                            <a class="dropdown-item" href="javascript:void(0);">TaskBoard</a>
                            <a class="dropdown-item" href="javascript:void(0);">Chat App</a>
                            <a class="dropdown-item" href="javascript:void(0);">Contacts</a>
                        </div>
                    </li>
                    </ul>
                    <form class="form-inline my-2 my-lg-0">
                        <button type="button" class="btn btn-primary">Add</button>
                        <a href="#" title="Portfolio" class="btn btn-success ml-2">Portfolio</a>
                    </form>
                </div>
            </nav>
            <div class="container-fluid">
                <div class="row clearfix">
                    <div class="col-lg-12 col-md-12">
                        <div class="card planned_task">
                            <div class="header">
                                <!-- <h2><a href="{{url('customer.index')}}">Manage Customer</a></h2> -->
                                <button class="btn btn-info "><a href="{{route('settings.index')}}">Manage Customer</a></button>
                            </div>
                            <div class="body">
                            <div class="col-md-12">
                        <div class="card">
                          
                            <div class="body">
                                <form id="basic-form" method="POST" action="{{route('settings.store')}}" >
                                    @csrf
                                    <div class="form-group">
                                        <label> Name   </label>
                                        <input type="text" name="name" class="form-control" placehoder="Company Name" required>
                                    </div>
                                    <div class="form-group">
                                        <label>Phone Number </label>
                                        <input type="phone" name="phone" class="form-control" placehoder="Company Phone" required>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label>Address </label>
                                        <textarea type="text" name="address" class="form-control" placehoder="Company Address" required></textarea>
                                    </div>
                                    <div class="form-group">
                                        <label>Email </label>
                                        <input type="email" name="email" class="form-control" placehoder="Company Email" required>
                                    </div>
                                    <div class="form-group">
                                        <label>Logo  </label>
                                        <input type="text" name="logo" class="form-control" placehoder="Company Logo" required>
                                    </div>
                                    <div class="form-group">
                                        <label>City  </label>
                                        <input type="text" name="city" class="form-control" placehoder="Company City" required>
                                    </div>
                                    <div class="form-group">
                                        <label>Country  </label>
                                        <input type="text" name="country" class="form-control" placehoder="Company Country" required>
                                    </div>
                                    <button type="submit" class="btn btn-primary">Add Settings </button>
                                </form>
                            </div>
                        </div>
                    </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
               
            @endsection

resources/views/settings/edit.blade.php
@extends('layouts.app')

@section('title')

Edit Setting
@endsection

@section("page")

<nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="{{url('/dashboard')}}">Dashboard</a>
                <a class="navbar-brand" href="{{url('/blank')}}">Contacts</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-align-justify"></i>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="javascript:void(0);" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Application</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="javascript:void(0);">Inbox</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="javascript:void(0);">Calendar</a>
                            <a class="dropdown-item" href="javascript:void(0);">TaskBoard</a>
                            <a class="dropdown-item" href="javascript:void(0);">Chat App</a>
                            <a class="dropdown-item" href="javascript:void(0);">Contacts</a>
                        </div>
                    </li>
                   
                    </ul>
                    <form class="form-inline my-2 my-lg-0">
                        <button type="button" class="btn btn-primary">Add</button>
                        <a href="https://themeforest.net/user/wrraptheme/portfolio" title="Portfolio" class="btn btn-success ml-2">Portfolio</a>
                    </form>
                </div>
            </nav>
            <div class="container-fluid">
                <div class="row clearfix">
                    <div class="col-lg-12 col-md-12">
                        <div class="card planned_task">
                            <div class="header">
                                <h2><a href="{{route('settings.index')}}">Manage Attendance</a></h2>
                            </div>
                            <div class="body">
                            <div class="col-md-12">
                        <div class="card">
                          
                            <div class="body">
                                <form id="basic-form" method="POST" action="{{ route('settings.update',$setting->id) }}" >
                                    @csrf
                                    @method('PUT')
                                    <div class="form-group">
                                        <label> Name   </label>
                                        <input type="text" name="name" value="{{$setting->name}}" class="form-control" placehoder="setting Name" required>
                                    </div>
                                    <div class="form-group">
                                        <label>Phone </label>
                                        <input type="text" name="phone" value="{{$setting->phone}}" class="form-control" placehoder="setting phone" required>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label>Address </label>
                                        <input type="text" name="address" value="{{$setting->address}}" class="form-control" placehoder="setting Address" required>
                                    </div>
                                    <div class="form-group">
                                        <label>Email </label>
                                        <input type="email" name="email" value="{{$setting->email}}" class="form-control" placehoder="setting email" required>
                                    </div>
                                    <div class="form-group">
                                        <label> Logo   </label>
                                        <input type="text" name="logo" value="{{$setting->logo}}" class="form-control" placehoder="setting Logo" required>
                                    </div>
                                    <div class="form-group">
                                        <label> City   </label>
                                        <input type="text" name="city" value="{{$setting->city}}" class="form-control" placehoder="setting City" required>
                                    </div>
                                    <div class="form-group">
                                        <label> Country   </label>
                                        <input type="text" name="country" value="{{$setting->country}}" class="form-control" placehoder="setting Country" required>
                                    </div>

                                    <button type="submit" class="btn btn-primary">Update Settings</button>
                                </form>
                            </div>
                        </div>
                    </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
               
            @endsection

resources/views/settings/index.blade.php
 
@extends('layouts.app')

@section('title')

settings 
@endsection

@section("page")


<nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="{{url('/dashboard')}}">Dashboard</a>
                <a class="navbar-brand" href="{{url('/blank')}}">Contacts</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-align-justify"></i>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="javascript:void(0);" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Application</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="javascript:void(0);">Inbox</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="javascript:void(0);">Calendar</a>
                            <a class="dropdown-item" href="javascript:void(0);">TaskBoard</a>
                            <a class="dropdown-item" href="javascript:void(0);">Chat App</a>
                            <a class="dropdown-item" href="javascript:void(0);">Contacts</a>
                        </div>
                    </li>
                  
                    </ul>
                    <form class="form-inline my-2 my-lg-0">
                        <button type="button" class="btn btn-primary">Add</button>
                        <a href="https://themeforest.net/user/wrraptheme/portfolio" title="Portfolio" class="btn btn-success ml-2">Portfolio</a>
                    </form>
                </div>
            </nav>
            <div class="container-fluid">
                <div class="row clearfix">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="header">
    
                            <button class="btn btn-info "><a href="{{route('settings.create')}}">Create Company Information</a></button>
                            </div>
                            <div class="body">
                                <div class="table-responsive">
                                <table class="table table-striped table-hover js-basic-example dataTable">
                                <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th >Name</th>
                                                <th >Phone  </th>
                                                <th>Addrss</th>
                                                <th >Email </th>
                                                <th > Logo  </th>
                                                <th>City</th>
                                                <th >Country </th>
                                                <th  style="float:left;text-align:center;">Action</th>
                                            </tr>
                                        </thead>
              <tbody>
                  @foreach($settings as $setting)
                  <tr>
                      
                      <td> {{$setting->id}}</td>
                      <td> {{$setting->name}} </td>
                      <td> {{$setting->phone}} </td>
                      <td> {{$setting->address}} </td>
                      <td> {{$setting->email}} </td>
                      <td> {{$setting->logo}} </td>
                      <td> {{$setting->city}} </td>
                      <td> {{$setting->country}} </td>
                      <td style="float:left;width:145px;">
                         <form action="{{route('settings.destroy',$setting->id)}}"method="POST">
                      <a class="btn btn-primary btn-sm" href="{{route('settings.show',$setting->id)}}">                  
                              View
                          </a>
                          <a class="btn btn-info btn-sm" href="{{route('settings.edit',$setting->id)}}">
              
                              Edit
                          </a>
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                            </form>  
                          </a>
                      </td>
                  </tr>
                 @endforeach
              </tbody>
          </table>
                                   
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    
            @endsection